# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8d3c77110bacfb15c9a4074dcfea641896844c0e12cc4497d9cd044f3a07524cf0f32e534a182aa99a44616d4da29777781bd2bba120da4c6f00bd141fe0854

test:
  secret_key_base: fa336548c275311493c3f7bbeba24511f8606db744bdfe33eb50a03124c4e1260269e2ed4f6d537d4af268db7cb708e0be5ba194bb7a5390f37f9a7753167b34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
